import http.client
import json
import os
import tempfile
import threading
import unittest
from unittest.mock import patch

from cerebro import server
from dep_operaciones import database, gestor_ordenes, gestor_pagos, security


class FullCustomerFlowE2ETests(unittest.TestCase):
    """Real HTTP flow proving registration through billing stays tenant-isolated."""

    def setUp(self):
        self.tmpdir = tempfile.TemporaryDirectory()
        self.previous_db_path = database.DB_PATH
        database.DB_PATH = os.path.join(self.tmpdir.name, "skilltwin-test.db")
        database.init_database()
        self.previous_persistent_flag = security.REQUIRE_PERSISTENT_SESSIONS
        security.REQUIRE_PERSISTENT_SESSIONS = True

        self.httpd = server.ThreadingTCPServer(("127.0.0.1", 0), server.CerebroHandler)
        self.port = self.httpd.server_address[1]
        self.thread = threading.Thread(target=self.httpd.serve_forever, daemon=True)
        self.thread.start()

    def tearDown(self):
        self.httpd.shutdown()
        self.httpd.server_close()
        self.thread.join(timeout=2)
        security.REQUIRE_PERSISTENT_SESSIONS = self.previous_persistent_flag
        database.DB_PATH = self.previous_db_path
        self.tmpdir.cleanup()

    def request(self, method, path, token=None, body=None, csrf=False):
        headers = {}
        if token:
            headers["Authorization"] = f"Bearer {token}"
        if body is not None:
            headers["Content-Type"] = "application/json"
        if csrf:
            status, csrf_data = self.request("GET", "/api/csrf-token")
            self.assertEqual(status, 200)
            headers["X-CSRF-Token"] = csrf_data["token"]
            headers["X-Session-ID"] = csrf_data["session_id"]

        conn = http.client.HTTPConnection("127.0.0.1", self.port, timeout=5)
        conn.request(method, path, body=json.dumps(body) if body is not None else None, headers=headers)
        response = conn.getresponse()
        raw = response.read().decode("utf-8")
        conn.close()
        try:
            data = json.loads(raw)
        except json.JSONDecodeError:
            data = raw
        return response.status, data

    def register(self, email, name):
        status, data = self.request(
            "POST",
            "/api/auth/register",
            body={"email": email, "password": "Password-123!", "nombre": name},
        )
        self.assertEqual(status, 201)
        return data["token"], data["user"]

    def test_complete_customer_flow_and_tenant_isolation(self):
        token_a, user_a = self.register("flow-a@example.com", "Flow A")
        token_b, user_b = self.register("flow-b@example.com", "Flow B")

        status, me = self.request("GET", "/api/auth/me", token_a)
        self.assertEqual(status, 200)
        self.assertEqual(me["user"]["email"], user_a["email"])

        # Chat is a real HTTP request; the LLM/clone engine is mocked so CI does not need an API key.
        with patch.object(server.motor_clonacion, "consultar_clon", return_value="Respuesta del SkillTwin A"):
            status, chat = self.request(
                "POST",
                "/api/chat-clon",
                token_a,
                {"id_clon": "rsanchez_cobol", "pregunta": "¿Cómo optimizo este código?"},
                csrf=True,
            )
        self.assertEqual(status, 200)
        self.assertTrue(chat["session_id"])

        status, history_a = self.request(
            "GET",
            f"/api/clon-historial?clon_id=rsanchez_cobol&session_id={chat['session_id']}",
            token_a,
        )
        self.assertEqual(status, 200)
        self.assertEqual(history_a["session_id"], chat["session_id"])

        # Customer A creates an order while attempting to spoof B's email.
        status, order_response = self.request(
            "POST",
            "/api/crear-orden",
            token_a,
            {
                "cliente_email": user_b["email"],
                "clon_id": "rsanchez_cobol",
                "cantidad_horas": 2,
                "descripcion_proyecto": "Proyecto de A",
                "requiere_contrato": True,
            },
            csrf=True,
        )
        self.assertEqual(status, 201)
        order_id = order_response["orden_id"]
        order = gestor_ordenes.obtener_orden(order_id)
        self.assertEqual(order["cliente_email"], user_a["email"])

        # Create the invoice generated by the billing stage, then exercise the real HTTP authorization.
        invoice_id, _ = gestor_pagos.crear_factura(
            order_id, user_a["email"], 200.0, 30.0, 2, 100.0, "Proyecto de A"
        )

        status, orders_a = self.request("GET", "/api/ordenes", token_a)
        self.assertEqual(status, 200)
        self.assertEqual({item["id"] for item in orders_a["ordenes"]}, {order_id})

        status, invoices_a = self.request("GET", "/api/facturas", token_a)
        self.assertEqual(status, 200)
        self.assertEqual({item["id"] for item in invoices_a["facturas"]}, {invoice_id})

        # B cannot access or mutate A's invoice, even with a valid CSRF token.
        status, payment_error = self.request(
            "POST",
            "/api/procesar-pago",
            token_b,
            {"factura_id": invoice_id, "metodo_pago": "tarjeta_credito"},
            csrf=True,
        )
        self.assertEqual(status, 403)
        self.assertIn("permisos", payment_error["error"])

        status, orders_b = self.request("GET", "/api/ordenes", token_b)
        self.assertEqual(status, 200)
        self.assertEqual(orders_b["ordenes"], [])

        status, invoices_b = self.request("GET", "/api/facturas", token_b)
        self.assertEqual(status, 200)
        self.assertEqual(invoices_b["facturas"], [])

        # A can reach the payment endpoint for its own invoice. Stripe/payment internals are mocked.
        with patch.object(server.gestor_pagos, "procesar_pago", return_value=(True, {"estado": "pagado"})):
            status, payment_ok = self.request(
                "POST",
                "/api/procesar-pago",
                token_a,
                {"factura_id": invoice_id, "metodo_pago": "tarjeta_credito"},
                csrf=True,
            )
        self.assertEqual(status, 200)
        self.assertTrue(payment_ok["success"])

    def test_foreign_chat_session_cannot_be_reused(self):
        with patch.object(server.motor_clonacion, "consultar_clon", return_value="ok"):
            status, chat_a = self.request(
                "POST",
                "/api/chat-clon",
                self.register("session-a@example.com", "Session A")[0],
                {"id_clon": "rsanchez_cobol", "pregunta": "A", "session_id": "shared"},
                csrf=True,
            )
            token_b, _ = self.register("session-b@example.com", "Session B")
            status_b, chat_b = self.request(
                "POST",
                "/api/chat-clon",
                token_b,
                {"id_clon": "rsanchez_cobol", "pregunta": "B", "session_id": chat_a["session_id"]},
                csrf=True,
            )

        self.assertEqual(status, 200)
        self.assertEqual(status_b, 200)
        self.assertNotEqual(chat_a["session_id"], chat_b["session_id"])


if __name__ == "__main__":
    unittest.main()
